import React from "react";
import Navbar from "../Components/Navbar";
import Image from "next/image"
import Footer from "../Components/Footer";
import Testimonials from "../Components/Testimonials";

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <div className="flex flex-col gap-[20px] w-full">
     
     
        <div className="px-[10px] md:px-[100px]">

      <Navbar />
        </div>
      <div className=" px-[10px] md:px-[100px]  flex flex-col lg:flex-row gap-[10px] w-full py-10">
        <div className="flex flex-col w-full lg:w-1/2 gap-[20px]">
          <h1 className="p-2 max-w-[100px] text-white bg-blueColor">
            About us
          </h1>
          <span className="text-[20px] max-w-[300px] text-blueColor font-[800] leading-6 uppercase">
            Second Abundantly Move That Cattle Perform Appen Land
          </span>
          <span>
            Give their their without moving were stars called so divide in
            female be moving night may fish him Give their their without moving
            were stars called so divide female be moving night may fish him own
            male vreated great Give their their without moving were. Stars
            called so divide female moving night may fish him own male created
            great opportunity deal.
          </span>
        </div>
        <div className="flex flex-col w-full lg:w-1/2">
            <Image src="/image/first.jpg" width={600} height={600} className="w-full h-full object-cover rounded-[12px]" />
        </div>
      </div>

      <div className="flex flex-col px-[10px] md:px-[100px]">
        <div className=" bg-[#015bb4]   rounded-md grid grid-cols-2 md:grid-cols-4">
            <div className="flex flex-col items-center border-r py-8">
                <h1 className="text-[18px] font-[800] text-white">4 Years</h1>
                <span className="text-[16px] text-white/80">Exprience</span>
            </div>
            <div className="flex flex-col items-center border-r py-8">
                <h1 className="text-[18px] font-[800] text-white">4 Years</h1>
                <span className="text-[16px] text-white/80">Exprience</span>
            </div>
            <div className="flex flex-col items-center border-r py-8">
                <h1 className="text-[18px] font-[800] text-white">4 Years</h1>
                <span className="text-[16px] text-white/80">Exprience</span>
            </div>
            <div className="flex flex-col items-center border-r py-8">
                <h1 className="text-[18px] font-[800] text-white">4 Years</h1>
                <span className="text-[16px] text-white/80">Exprience</span>
            </div>
        </div>
      </div>

      <Testimonials/>


      <div className="flex flex-col gap-[40px] w-full items-center md:items-start px-[10px] md:px-[100px] py-10">
        <div className="flex flex-col ">
            <h1 className="text-[24px] font-[800]">Our Team</h1>
            <span>inventore facilis blanditiis dolor omnis pariatur, soluta nobis!</span>
        </div>
        <div className="w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-[20px]">
            <div className="flex flex-col gap-[10px]">
                <div className="w-full h-[40vh] ">
                    <Image src={`/image/profile1.jpg`} width={500} height={500} className="w-full h-full object-cover rounded-t-[8px]"/>
                </div>
                <div className="flex flex-col">
                    <h1 className="text-[18px] font-[600]">Byiringiro Aime</h1>
                    <span className="text-[16px] text-gray-500">CEO</span>

                </div>
            </div>
            <div className="flex flex-col gap-[10px]">
                <div className="w-full h-[40vh] ">
                    <Image src={`/image/profile3.jpg`} width={500} height={500} className="w-full h-full object-cover rounded-t-[8px] "/>
                </div>
                <div className="flex flex-col">
                    <h1 className="text-[18px] font-[600]">Byiringiro Aime</h1>
                    <span className="text-[16px] text-gray-500">Phatmant</span>

                </div>
            </div>
            <div className="flex flex-col gap-[10px]">
                <div className="w-full h-[40vh] ">
                    <Image src={`/image/profile2.jpg`} width={500} height={500} className="w-full h-full object-cover rounded-t-[8px]"/>
                </div>
                <div className="flex flex-col">
                    <h1 className="text-[18px] font-[600]">Byiringiro Aime</h1>
                    <span className="text-[16px] text-gray-500">Doctor</span>

                </div>
            </div>
            <div className="flex flex-col gap-[10px]">
                <div className="w-full h-[40vh] ">
                    <Image src={`/image/profile5.webp`} width={500} height={500} className="w-full h-full object-cover rounded-t-[8px]"/>
                </div>
                <div className="flex flex-col">
                    <h1 className="text-[18px] font-[600]">Byiringiro Aime</h1>
                    <span className="text-[16px] text-gray-500">NURSE</span>

                </div>
            </div>
        </div>
        

      </div>
      <Footer/>
    </div>
  );
};

export default AboutUs;
